### ISSUE TITLE
Error adding Nodon  sin-2-2-01 OH3.0

### ISSUE THREAD

**Issue by vio2000** [fruggy83/openocean#104]
Hi @fruggy83 ,
when I try to add a new nodon SIN-2-2-01, I get an error:

**2021-02-09 15:45:53.779 [INFO ] [ernal.transceiver.EnOceanTransceiver] - Received teach in message from 0584D1AA
2021-02-09 15:45:53.781 [INFO ] [covery.EnOceanDeviceDiscoveryService] - EnOcean Package discovered, RORG RPS, payload F6000584D1AA21, additional 00FFFFFFFF4F00
2021-02-09 15:45:53.784 [WARN ] [fig.discovery.DiscoveryResultBuilder] - Representation property '0584D1AA' of discovery result for thing 'enocean:pushButton:USB:0584D1AA' is missing in properties map. It has to be fixed by the bindings developer.
	at org.openhab.binding.enocean.internal.discovery.EnOceanDeviceDiscoveryService.packetReceived(EnOceanDeviceDiscoveryService.java:141)
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:283)
	at org.openhab.binding.enocean.internal.transceiver.EnOceanESP3Transceiver.processMessage(EnOceanESP3Transceiver.java:151)
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:254)
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:191)**

Can you tell me the reason for this error? 

I added this device already in a things-file like this:
**Thing measurementSwitch 0584D1AA "EN Switch Oliver" [ enoceanId="0584D1AA", senderIdOffset=12, sendingEEPId="D2_01_12_NODON", receivingEEPId="D2_01_12_NODON"   ]**
but it doesn't work correctly. It only shows the state, but doesn't react on any input in OH3.0

Thanks in advance
@vio2000

**Comment by fruggy83** [comment]
Hi @vio2000 ,

there was a API change in OH3. I have already fixed this problem and I am working on a PR.

Best regards
Daniel

**Comment by fruggy83** [comment]
Hi @vio2000 

Sorry I just read the first part up to the end of the call stack.
Your thing configuration looks ok. My PSC switch works with this configuration:
`Thing measurementSwitch 05038393 "PSC234" [ enoceanId="05038393", senderIdOffset=4, sendingEEPId="D2_01_09_PERMUNDO", receivingEEPId="D2_01_09_PERMUNDO","A5_12_01", broadcastMessages=false, suppressRepeating=false, pollingInterval=3600]`

If you have already teached your senderIdOffset 12 into your NodON, you could try to add the broadcastMessages parameter to your config. Most UPE actuators like your NodON do not support/expect broadcast messages. I am not sure but this parameter could be set to true by default. Give it a try.

Best regards
Daniel

**Comment by vio2000** [comment]
How do I teachin the NodON devices? I didn't find any documentation

**Comment by vio2000** [comment]
Well, the things are receiving the states like ON/OFF or 0-100% open or last received... But I can't use them with OH. No reaction at all, even after a complete new teachin. 
Please help

**Comment by vio2000** [comment]
hi @fruggy83,
I'm still facing the problem. 
One strange thing that happens is, when remove the thing from the things-file, clean the cache and restart openhab, then add the thing by discovery the adding process ignores the nextdeviceid set in the bridge totally. The thing is always added with the same deviceid like before. Even when I reset the nodOn device, the same effect appears. Can you tell me why??
What do I have to do, to get the device added correctly?
When I use my second USB300 stick on my windows laptop and a clean OH installation, the device is added correctly and is working fine??
Sounds pretty strange??
Thanks for your support
